name: "Setup conda"
description: "Install conda Miniconda or Anaconda."

inputs:
  installer:
    description: "Version of conda to install"
    required: true
    default: "Anaconda"
  version_anaconda:
    description: "Version of Anaconda to install"
    required: false
    default: "2021.05"
  version_miniconda:
    description: "Version of Miniconda to install"
    required: false
    default: "latest"

outputs:
  cache-path:
    description: "Path to the conda installer, e.g. for use with actions/cache."
    value: ${{ steps.install.outputs.cache-path }}

runs:
  using: "composite"
  steps:
  - name: Install conda
    id: install
    env:
      RUNNER_OS: ${{ runner.os }}
      INSTALLER: ${{ inputs.installer }}
      VERSION_ANACONDA: ${{ inputs.version_anaconda }}
      VERSION_MINICONDA: ${{ inputs.version_miniconda }}
      GHA_PATH: ${{ github.action_path }}
    run: ${GITHUB_ACTION_PATH}/script.sh
    shell: bash

  - name: Confirm conda is on PATH
    run: conda
    shell: bash
