name: "Setup GAMS"
description: "Install the GAMS executable."

inputs:
  license:
    description: "Content for gamslice.txt, e.g. from a repo secret."
    require: false
    default: null
  # use-cache:
  #   description: "Cache the GAMS installer."
  #   required: false
  #   default: true
  version:
    description: "Version of GAMS to install"
    required: false
    default: "25.1.1"

runs:
  using: "composite"
  steps:
  # Disabled: recursive usage is not supported
  # - name: Cache GAMS installer
  #   if: ${{ inputs.use-cache }}
  #   uses: actions/cache@v2
  #   with:
  #     path: |
  #       gams
  #     key: ${{runner.os}-gams${{ inputs.version }}
  #     restore-keys: |
  #       ${{ runner.os }}-gams${{ inputs.version }}-
  #       ${{ runner.os }}-

  - name: Install GAMS
    env:
      CI_OS: ${{ runner.os }}
      GAMS_VERSION: ${{ inputs.version }}
    run: ${GITHUB_ACTION_PATH}/script.sh
    shell: bash

  - name: Set up GAMS license
    env:
      GAMS_LICENSE: ${{ inputs.license }}
    run: |
      if [ -n "$GAMS_LICENSE" ]; then
        echo "$GAMS_LICENSE" > $(dirname $(which gams))/gamslice.txt
        gams
      fi
    shell: bash
