# Verify that the setup-conda action works
#
# When modifying the action in a PR, set the "uses:" entries to "…@branch-name"
# to test the modified code on the branch.

name: Validate setup-conda action
on:
  push:
    # TODO remove feature/setup-conda-action once #2 is merged
    branches: [ main, feature/setup-conda-action ]
  pull_request:
    branches: [ main ]

jobs:
  conda:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        conda: [anaconda, miniconda]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.conda }}

    steps:
    - name: Setup anaconda (defaults)
      if: ${{ matrix.conda == 'anaconda' }}
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      # NB no "with:" section → defaults are used

    - name: Setup miniconda (py39_4.10.3)
      if: ${{ matrix.conda == 'miniconda' }}
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      with:
        installer: ${{ matrix.conda }}
        version: py39_4.10.3

    - name: Check conda version and location
      run: conda info
