# Verify that the setup-conda action works

name: Validate setup-conda action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conda:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        conda: [anaconda, miniconda]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.conda }}

    steps:  
    - name: Setup anaconda
      if: ${{ matrix.conda == 'anaconda' }}
      # Todo change branch back to `main`
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      with:
        installer: ${{ matrix.conda }}
        version: 2021.05

    - name: Setup miniconda
      if: ${{ matrix.conda == 'miniconda' }}
      # Todo change branch back to `main`
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      with:
        installer: ${{ matrix.conda }}
        version: py39_14.10.3

    - name: Check conda version
      run: conda --version

